spring.application.name=backend

server.port=${SERVER_PORT:9090}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/dogclinic}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=Slayer@King1234

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

jwt.secret=6iolmWafWO0U0itNY/bs9wwG6NTCTqJcFLO3rpCSHfoGRp1o0s/jHbyFwBaRnDYexLZtMgidoizNRuzKREeN6g==

admin.username=${ADMIN_USERNAME:admin}
admin.password=12345
admin.email=${ADMIN_EMAIL:admin@gmail.com}

spring.jpa.open-in-view=false
test.marker=HELLO123

cloudinary.cloud-name=e8q3eqmp
cloudinary.api-key=159425518214395
cloudinary.api-secret=pgvUVVczeJbpSY5mSsjpPZO3ohA

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB